name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:ci

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: 'npm'
      - run: npm ci
      - run: npm run type-check

  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11
          cache: 'npm'
      - run: npm ci
      - run: echo "${{ vars.ENV_FILE }}" >> .env
      - run: npm run codeceptjs:headless

  notification:
    if: always()
    needs: [ codestyle, test ]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
               --url https://api.telegram.org/bot${{ secrets.TEST_TELEGRAM_TOKEN }}/sendMessage \
               --header 'Content-Type: application/json' \
                --data '{ "chat_id": "${{ secrets.TEST_TELEGRAM_CHAT_ID }}", "text": "Report link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'